version: 2
jobs:
  merge-upstream:
    working_directory: ~/mybgg
    docker:
      - image: circleci/python:3.6.4
    steps: # a collection of executable commands
      - checkout # special step to check out source code to the working directory
      - run:
          command: |
            git remote add upstream https://github.com/EmilStenstrom/mybgg
            git fetch upstream
            git rebase upstream/master
            git push -f origin master
  update-algolia:
    working_directory: ~/mybgg
    docker:
      - image: circleci/python:3.6.4
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps: # a collection of executable commands
      - checkout # special step to check out source code to the working directory
      - restore_cache: # restores saved dependency cache if the Branch key template or requirements.txt files have not changed since the previous run
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run: # install and activate virtual environment with pip
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache: # special step to save dependency cache
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run: # update algolia index
          command: |
            . venv/bin/activate
            python download_and_index.py --apikey $ALGOLIA_API_KEY
workflows:
  version: 2
  commit:
    jobs:
      - update-algolia
  nightly:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - merge-upstream
      - update-algolia:
          requires:
            - merge-upstream
